sudo: required
services:
  - docker

script:
  - docker build -t clgxaweeks/node-test .
  - docker images clgxaweeks/node-test

before_deploy:
  - docker login -u clgxaweeks -p TestPassword!

deploy:
  provider: script
  script: docker push clgxaweeks/node-test
  on:
    branch: main
